### ISSUE TITLE
Improve performance near poles

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#117]
- [ ] Investigate memory usage near poles (#118)
- [ ] Investigate CPU and GPU usage near poles (#119)
- [ ] Camera near pole causes OutOfMemoryError (#116)
