### ISSUE TITLE
Basic line of sight visualization

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#130]
Establish support for basic line of sight visualization in WorldWindAndroid. This basic initial iteration is implemented as a WorldWind Renderable object that applications add to a Layer. When the line of sight Renderable is in view, it draws the visible terrain fragments within a limited field of view as solid color displayed on top of the base map. For this basic initial iteration, the line of sight Renderable is configurable with the following properties:
- Position (latitude, longitude, altitude)
- Heading
- Altitude mode (absolute, clamp-to-ground, relative-to-ground)
- Sight distance range (near, far)
- Field of view
- Color (including opacity)

Implementation stories:
- [x] Basic line of sight interface (#131)
- [x] Depth-only drawing mode (#132)
- [x] Perspective render-to-texture (#133)
- [x] Basic line of sight renderable (#134)
- [x] Line of site tutorial and example (#148)
