### ISSUE TITLE
Update WorldWind Android documentation

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/WorldWindAndroid#140]
Update the overall documentation in the WorldWind Android repository.

1. Add several new files which outline the project's contribution guidelines. It is designed for both the WorldWind team and any users who wish to open an issue or pull request in the WorldWind Android repository.

2. Make "WorldWind" the name standard (as opposed to "World Wind"). This will ensure that the project name is consistent with the website and all other project repositories.

Implementation stories:

 

- [x] Add CONTRIBUTING.md [(#141)](https://github.com/NASAWorldWind/WorldWindAndroid/issues/141)
- [x] Add ISSUE_TEMPLATE.md [(#142)](https://github.com/NASAWorldWind/WorldWindAndroid/issues/142)
- [x] Add PR_TEMPLATE.md [(#143)](https://github.com/NASAWorldWind/WorldWindAndroid/issues/143)
- [x] Make "WorldWind" the name standard [#144](https://github.com/NASAWorldWind/WorldWindAndroid/issues/144)
